version: "3"

services:
  fastapi:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - .:/app
    env_file:
      - .env

  streamlit:
    build: .
    container_name: streamlit_container
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app-network
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
